name: CI
on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]
jobs:
  pre-commit:
    name: PreCommit
    runs-on: ubuntu-latest
    steps:
    - uses: NixOS/nix-installer-action@228d8a956062db04221c97c2794ea443194824aa
    - name: Checkout
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: nix checks
      run: nix flake check
    - name: nix pre-commit
      run: nix develop . --command pre-commit run --show-diff-on-failure
