name: CI

concurrency:
  group: "tests"
  cancel-in-progress: false

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    name: create package matrix
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      with:
        diagnostic-endpoint: ""
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - id: matrix
      run: |
        _matrix=$(nix flake show --json --all-systems | jq -r '.packages."x86_64-linux" | keys')
        echo "matrix=${_matrix}" >> $GITHUB_OUTPUT

  tests-and-build:
    if: github.event.pull_request.draft == false
    needs: [create-matrix]
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}
    steps:
    - uses: DeterminateSystems/nix-installer-action@e50d5f73bfe71c2dd0aa4218de8f4afa59f8f81d # v16
      with:
        diagnostic-endpoint: ""
    - name: Check out code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Test ${{ matrix.test }}
      run: nix build -L .#${{ matrix.test }}
