name: CI

concurrency:
  group: "tests"
  cancel-in-progress: false

on:
  push:
    branches:
    - main
  pull_request:
    types: [opened, synchronize, ready_for_review, reopened]

jobs:
  create-matrix:
    runs-on: ubuntu-latest
    name: create package matrix
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
    - uses: NixOS/nix-installer-action@6b8548fe06acfb0155a50ab5d561accb215764cc
      with:
        extra-conf: |
          experimental-features = nix-command flakes
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - id: matrix
      run: |
        nix flake show --json --all-systems | jq -cr '.packages."x86_64-linux" | keys' > _temp
        echo $(cat _temp)
        echo "matrix=$(cat _temp)" >> $GITHUB_OUTPUT

  tests-and-build:
    if: github.event.pull_request.draft == false
    needs: [create-matrix]
    name: tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.create-matrix.outputs.matrix) }}
    steps:
    - uses: NixOS/nix-installer-action@6b8548fe06acfb0155a50ab5d561accb215764cc
      with:
        extra-conf: |
          experimental-features = nix-command flakes
    - name: Check out code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
    - name: Test ${{ matrix.test }}
      run: nix build -L .#${{ matrix.test }}
